version: "3.9"  # Docker Compose version

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=your_db_password
      - DB_NAME=gin-web-api

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=gin-web-api